---
name: Docker Build & Push
description: Build the docker image and push it to the registry

inputs:
  DOCKERFILE_PATH:
    description: "path to the Dockerfile to build and push"
    required: true
    default: ""
  DOCKER_IMAGE:
    description: "name of the image on the remote registry"
    required: true
    default: ""
  DOCKER_HUB_USERNAME:
    description: "username to push the built image"
    required: true
    default: ""
  DOCKER_HUB_TOKEN:
    description: "token to push the built image"
    required: true
    default: ""
  TAG:
    description: "tag to use to build the image"
    required: true
    default: ""

runs:
  using: "composite"
  steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ inputs.DOCKERHUB_USERNAME }}
        password: ${{ inputs.DOCKERHUB_TOKEN }}

    - name: Build & Push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ${{ inputs.DOCKERFILE_PATH }}
        push: true
        tags: |
          ${{ inputs.DOCKER_IMAGE }}:${{ inputs.TAG }}
